### ISSUE TITLE
Unsupported ubuntu based distribution

### ISSUE THREAD

**Issue by Vin985** [mherrmann/fbs#67]
Hi,
Your application should be able to create packages for ubuntu, but Linux Mint (which is based on ubuntu) is not recognized as an Ubuntu distribution.

I don't know if this is normal but I believe the problem comes from the fact that according to the code, distribution is based on the NAME entry of the /etc/os-release file. 
Since the same file can show that it is based on ubuntu (see below), I was wondering if supporting such distributions would be possible or not.

$ cat /etc/os-release
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial

On a side note, this seem to cause another kind of problem as when I try to run fbs installer, I get the following error 

Traceback (most recent call last):
  File "/home/vin/testenv/bin/fbs", line 11, in <module>
    load_entry_point('fbs==0.5.5', 'console_scripts', 'fbs')()
  File "/home/vin/testenv/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/home/vin/testenv/lib/python3.6/site-packages/fbs/cmdline.py", line 31, in main
    fn(*args)
  File "/home/vin/testenv/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 146, in installer
    out_file = join('target', SETTINGS['installer'])
KeyError: 'installer'

This seem to come from the fact that in none of the settings files I have in src/build/settings (I have a base.json, linux.json and mac.json) there is an "installer" property. If I add one manually like the one you can find in the default ubuntu.json, the error goes away and I only get an "Unsupported Linux distribution" message.

Thanks

**Comment by mherrmann** [comment]
Thanks! I fixed this in release 0.5.6 so `is_ubuntu()` now returns `True` on Linux Mint. This should make everything work just as on Windows.

**Comment by Vin985** [comment]
Thank you for your very quick fix!
Unfortunately this still doesn't work because os_release name is splitted by whitespace in _get_linux_distribution() so the result of this function is not "Linux Mint" but "Linux" and thus the is_ubuntu() function still doesn't recognize it.

Otherwise, by removing the split, everything seems to work perfectly!

Thanks

**Comment by mherrmann** [comment]
I see, sorry. I just released [v0.5.9](https://github.com/mherrmann/fbs/releases/tag/v0.5.9). Does it work for you now?

**Comment by Vin985** [comment]
Yes it works perfectly now, thanks!

**Comment by LeastSignificantBit** [comment]
Hi,
This is a problem on Debian too.
I fixed it by adding:
'Debian GNU/Linux'
to the list in is_ubuntu()

Cheers!

**Comment by mherrmann** [comment]
Thanks for sharing @LeastSignificantBit. I actually had the exact same problem on my computer recently, when I switched from Ubuntu to Xfce.
